---
# tasks file for create_test_db
- name: create_test_db
  debug:
    msg: "create_test_db!"

- name: create db otus
  become_user: postgres
  community.general.postgresql_db:
    name: otus

- name: Ensure user has access to the database
  become: true
  become_user: postgres
  postgresql_user: 
    db: otus
    name: django
    password: pass123pass
    encrypted: yes
    priv: ALL
    state: present

- name: Ensure user does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user: 
    name: django
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present

- name: create barman user
  become_user: postgres
  community.general.postgresql_user:
    name: barman
    password: barman_pass
    role_attr_flags: SUPERUSER,REPLICATION