---
ip_gateway: "192.168.255.1"
lineinfile:
  - path: '/etc/sysconfig/network-scripts/ifcfg-eth0'
    regexp: '^DEFROUTE='
    line: 'DEFROUTE=no'
  - path: '/etc/sysconfig/network-scripts/ifcfg-eth1'
    regexp: '^GATEWAY='
    line: 'GATEWAY={{ ip_gateway }}'

  # - path: "/etc/sysconfig/network-scripts/route-eth1"
  #   line: "default via {{ ip_gateway }} dev eth1"
  #   regexp: "^default via"

  # - path: '/etc/sysconfig/network-scripts/ifcfg-eth7'
  #   regexp: '^IPADDR1='
  #   line: 'IPADDR1=192.168.0.49'
  # - path: '/etc/sysconfig/network-scripts/ifcfg-eth7'
  #   regexp: '^NETMASK1='
  #   line: 'NETMASK1=255.255.255.240'

  # - path: '/etc/sysconfig/network-scripts/ifcfg-eth7'
  #   regexp: '^IPADDR2='
  #   line: 'IPADDR2=192.168.0.129'
  # - path: '/etc/sysconfig/network-scripts/ifcfg-eth7'
  #   regexp: '^NETMASK2='
  #   line: 'NETMASK2=255.255.255.128'

  # - path: '/etc/sysconfig/network-scripts/route-eth5'
  #   regexp: '^192.168.2.0/24'
  #   line: '192.168.2.0/24 via 192.168.255.6'

  # - path: '/etc/sysconfig/network-scripts/route-eth6'
  #   regexp: '^192.168.1.0/24'
  #   line: '192.168.1.0/24 via 192.168.255.10'