# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/8"

#  config.vm.provision "ansible" do |ansible|
# #    ansible.verbose = "vvv"
#    ansible.playbook = "playbook.yml"
#    ansible.become = "true"
#    ansible.groups = {
#       "nfsclient" => ["nfsc"],
#       "nfsserver" => ["nfss"]
#     }
#  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1000
    v.cpus = 3
  end

  config.vm.define "zfs" do |zfs|
    zfs.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    zfs.vm.hostname = "zfs"
  end


end