---

dependencies: []

galaxy_info:
  author: Sergei Antipov
  company: 2GIS
  description: Prometheus exporters common tasks
  license: GPLv2
  min_ansible_version: 2.0
  platforms:
  - name: Debian
    versions:
    - jessie
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags:
  - monitoring
