---
# tasks file for master-setup
- name: Initialize the Database
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  args:
    creates: /var/lib/pgsql/11/data/postgresql.conf

- name: config master postgresql.conf
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: /var/lib/pgsql/11/data/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0600'
  notify:
    - restart postgres

- name: config master
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /var/lib/pgsql/11/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'
  notify:
    - restart postgres

- name: postgresql enable and start
  systemd:
    name: postgresql-11
    state: started
    enabled: yes

- name: wait for port postgres
  wait_for: 
    host: 127.0.0.1
    port: 5432 
    timeout: 1
- name: create remote template
  file: 
    path: /var/lib/pgsql/.ansible/tmp
    owner: postgres
    group: postgres
    mode: '0700'
    recurse: true
    
# - name: create barman user
#   become_user: postgres
#   community.general.postgresql_user:
#     name: barman
#     password: barman_pass
#     role_attr_flags: SUPERUSER,REPLICATION