---
# tasks file for rsyslog-server
- name: install epel-release
  ansible.builtin.yum:
    name:
      - epel-release

- name: install pkg rsyslog
  ansible.builtin.yum:
    name:
      - rsyslog
    state: present

- name: config rsyslog server
  template:
    src: syslog-server.conf
    dest: /etc/rsyslog.d/server.conf
  notify: restart rsyslog


  