---
# tasks file for base
- name: DNS hosts server
  lineinfile:
    path: "/etc/hosts"
    regexp: "^{{ item.ip }}"
    line: "{{ item.ip }} {{ item.fqdn }}"
  loop:
    - ip: "192.168.255.2"
      fqdn: "nginx"
    - ip: "192.168.255.3"
      fqdn: "app1"
    - ip: "192.168.255.4"
      fqdn: "app2"
    - ip: "192.168.255.5"
      fqdn: "db1"
    - ip: "192.168.255.6"
      fqdn: "db2"
    - ip: "192.168.255.7"
      fqdn: "backup"
    - ip: "192.168.255.8"
      fqdn: "log"
    - ip: "192.168.255.9"
      fqdn: "monitoring"

- name: install epel-release
  ansible.builtin.yum:
    name:
      - epel-release

- name: install pkg
  yum:
    name: 
      - rsync
      - tree
      - htop
      - tcpdump
      - mc