# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.1.101',
	      :memory => "256",
  },
  :bacula => {
        :box_name => "centos/7",
        :ip_addr => '192.168.1.102',
	      :memory => "512", 
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "public_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
	        vb.memory = boxconfig[:memory]  
          vb.name = boxname.to_s
            
        end
        
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
   SHELL
      case boxname.to_s
      when "client"
      box.vm.provision "shell", run: "always", inline: <<-SHELL
      yum install -y vim bacula-client
      /bin/cp -f /vagrant/bacula-fd.conf /etc/bacula/
      systemctl start bacula-fd
      SHELL

     when "bacula"
     box.vm.provision "shell", run: "always", inline: <<-SHELL
     yum install -y bacula-director-mysql bacula-storage-mysql bacula-console mariadb-server vim
     systemctl start mariadb
     systemctl enable mariadb

     /usr/libexec/bacula/grant_mysql_privileges
     /usr/libexec/bacula/create_mysql_database -u root
     /usr/libexec/bacula/make_mysql_tables -u bacula

     mysql -e "UPDATE mysql.user SET Password=PASSWORD('bacula') WHERE User='bacula';"
     mysql -e "UPDATE mysql.user SET Password = PASSWORD('123456') WHERE User = 'root'"
     mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
     mysql -e "DROP USER ''@'localhost'"
     mysql -e "DROP USER ''@'$(hostname)'"
     mysql -e "DROP DATABASE test"

     mysql -e "FLUSH PRIVILEGES"
      
     echo 1 | alternatives --config libbaccats.so

     mkdir -p /bacula/backup /bacula/restore
     chown -R bacula:bacula /bacula
     chmod -R 700 /bacula

      /bin/cp -f /vagrant/{bacula-dir.conf,bacula-sd.conf,bconsole.conf} /etc/bacula/
      systemctl enable --now {bacula-dir,bacula-sd}

     
      SHELL

end
  end
  end
end
