---
# defaults file for base
hosts_dns:
  - ip: "192.168.255.2"
    fqdn: "nginx"
  - ip: "192.168.255.3"
    fqdn: "app1"
  - ip: "192.168.255.4"
    fqdn: "app2"
  - ip: "192.168.255.5"
    fqdn: "db1"
  - ip: "192.168.255.6"
    fqdn: "db2"
  - ip: "192.168.255.7"
    fqdn: "backup"
  - ip: "192.168.255.8"
    fqdn: "log"
  - ip: "192.168.255.9"
    fqdn: "monitoring"

sysctl_settings:
  - { name: 'vm.swappiness', value: '10'}
  - { name: 'net.core.rmem_max', value: '16777216' }
  - { name: 'net.core.wmem_max', value: '16777216' }
  - { name: 'net.ipv4.tcp_rmem', value: '4096 87380 16777216' }
  - { name: 'net.ipv4.tcp_wmem', value: '4096 65536 16777216' }
  - { name: 'net.ipv4.tcp_max_orphans', value: '65536' }
  - { name: 'net.ipv4.tcp_fin_timeout', value: '10' }
  - { name: 'net.ipv4.tcp_keepalive_time', value: '1800' }
  - { name: 'net.ipv4.tcp_keepalive_intvl', value: '15' }
  - { name: 'net.ipv4.tcp_keepalive_probes', value: '5' }
  - { name: 'net.ipv4.tcp_max_syn_backlog', value: '4096' }
  - { name: 'net.ipv4.tcp_synack_retries', value: '1' }
  - { name: 'net.core.somaxconn', value: '65535' }
  - { name: 'net.core.netdev_max_backlog', value: '1000' }
  - { name: 'net.ipv4.ip_local_port_range', value: '2000 65535' }
  - { name: 'net.ipv4.tcp_syncookies', value: '0' }
  - { name: 'net.ipv4.tcp_congestion_control', value: 'htcp' }
  - { name: 'net.ipv4.tcp_tw_reuse', value: '0' }
  - { name: 'net.ipv4.tcp_rfc1337', value: '1' }
  - { name: 'fs.file-max', value: '2097152' }
limit_files:
  - {domain: "root", type: "soft", item: "nofile", value: "100000"}
  - {domain: "*", type: "soft", item: "nofile", value: "100000"}
  - {domain: "root", type: "hard", item: "nofile", value: "100000"}
  - {domain: "*", type: "hard", item: "nofile", value: "100000"}
