---
# tasks file for rsyslog-client
- name: install epel-release
  ansible.builtin.yum:
    name:
      - epel-release

- name: install pkg rsyslog
  ansible.builtin.yum:
    name:
      - rsyslog
    state: present

- name: config rsyslog client
  template:
    src: syslog-client.conf
    dest: /etc/rsyslog.d/client.conf
  notify: restart rsyslog
