---
- name: Hello play
  become: true
  hosts: all
  tasks:
    - name: Hello
      debug:
        msg: "Hello!"

- name: базовая настройка
  hosts: all
  become: yes
  roles:
    - base

- hosts: all
  become: true
  roles:
    - role: UnderGreen.prometheus-node-exporter

- name: Настройка сервера логов
  hosts: log
  become: yes
  roles:
    - rsyslog-server

- name: Настройка отправки логов
  hosts: all
  become: yes
  roles:
    - rsyslog-client

- name: borgbackup servers
  become: true
  hosts: borgbackup_servers
  roles:
    - fiaasco.borgbackup

- name: borgbackup client
  become: true
  hosts: borgbackup_client
  roles:
    - fiaasco.borgbackup

- name: Установка postgres11
  hosts: db1, db2, backup
  become: yes
  roles:
    - postgres_install

- name: Настройка master
  hosts: db1
  become: yes
  roles:
    - master-setup

- name: Настройка slave
  hosts: db2
  become: yes
  roles:
    - slave-setup

- name: Создание тестовой БД
  hosts: db1
  become: yes
  roles:
    - create_test_db

- name: Настройка barman
  hosts: backup
  become: yes
  roles:
    - barman_install
