Vagrant.configure("2") do |config|

  config.vm.define "pxeserver" do |server|
    config.vm.box = 'centos/8.2'
    config.vm.box_url = 'https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.2.2004-20200611.2.x86_64.vagrant-virtualbox.box'
    config.vm.box_download_checksum = '698b0d9c6c3f31a4fd1c655196a5f7fc224434112753ab6cb3218493a86202de'
    config.vm.box_download_checksum_type = 'sha256'
  
    server.vm.host_name = 'pxeserver'
    server.vm.network :private_network, 
                       ip: "10.0.0.20", 
                       virtualbox__intnet: 'pxenet'
  
    # server.vm.network "forwarded_port", guest: 80, host: 8081
  
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  
    # ENABLE to setup PXE
    server.vm.provision "ansible" do |ansible|
      # ansible.verbose = "v"
      ansible.playbook = "provision.yml"
      ansible.become = "true"
      # ansible.groups = {
      #     "borgbackup_client" => ["client"],
      #     "borgbackup_servers" => ["server"]
      #   }
      ansible.raw_arguments = ['--diff']
    end
  
  end
  # Cent OS 8.2
  # config used from this
  # https://github.com/eoli3n/vagrant-pxe/blob/master/client/Vagrantfile
    config.vm.define "pxeclient" do |pxeclient|
      pxeclient.vm.box = 'centos/8.2'
      pxeclient.vm.host_name = 'pxeclient'
      pxeclient.vm.network :private_network, ip: "10.0.0.21"
      pxeclient.vm.provider :virtualbox do |vb|
        vb.memory = "2048"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize [
            'modifyvm', :id,
            '--nic1', 'intnet',
            '--intnet1', 'pxenet',
            '--nic2', 'nat',
            '--boot1', 'net',
            '--boot2', 'none',
            '--boot3', 'none',
            '--boot4', 'none'
          ]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end
        # ENABLE to fix memory issues
  #     end
    end
  
  end