# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                   {ip: '192.168.255.5', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "router-office1"},
                   {ip: '192.168.255.9', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "router-office2"},
                   {ip: '192.168.0.17', adapter: 8, netmask: "255.255.255.240", virtualbox__intnet: "central-newnet1"},
                #    {ip: '192.168.0.49', adapter: 9, netmask: "255.255.255.240", virtualbox__intnet: "central-newnet2"},
                #    {ip: '192.168.0.129', adapter: 10, netmask: "255.255.255.128", virtualbox__intnet: "central-newnet3"},
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.34', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.66', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                   {ip: '192.168.0.18', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "central-newnet1"},
                   {ip: '192.168.0.50', adapter: 6, netmask: "255.255.255.240", virtualbox__intnet: "central-newnet1"},
                   {ip: '192.168.0.130', adapter: 7, netmask: "255.255.255.128", virtualbox__intnet: "central-newnet1"},  
                ]
  },

  :office1Router => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-office1"},
               {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "office1-net1"},
               {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office1-net2"},
               {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office1-net3"},
               {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "office1-net4"},

            ]
},

  :office1Server => {
    :box_name => "centos/7",
    :net => [
                {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-net1"},
                {ip: '192.168.2.66', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "office1-net2"},
                {ip: '192.168.2.130', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office1-net3"},
                {ip: '192.168.2.194', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office1-net4"},
            ]
},

:office2Router => {
    :box_name => "centos/7",
    :net => [
                {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-office2"},
                {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "office2-net1"},
                {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office2-net2"},
                {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-net3"},
            ]
},

  :office2Server => {
    :box_name => "centos/7",
    :net => [
                {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.128", virtualbox__intnet: "office2-net1"},
                {ip: '192.168.1.130', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "office2-net2"},
                {ip: '192.168.1.194', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office2-net3"},
            ]
},
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        box.vm.provision 'ansible' do |ansible|
            # ansible.verbose = "v"
            ansible.groups = { 
                "all" => ["office2Server", 
                            "office2Router", 
                            "office1Server", 
                            "office1Router", 
                            "centralServer", 
                            "centralRouter", 
                            "inetRouter"
                        ],
                "routers" => [ "office1Router",
                                "office2Router",
                                "centralRouter"
                            ],
                "servers" => [ "centralServer",
                                "office1Server",
                                "office2Server"
                            ]

            }
            ansible.become = true
            ansible.host_key_checking = false
            ansible.playbook = "provision.yaml"
        end

      end

  end
  
  
end
