---
ip_gateway: "192.168.0.1"

lineinfile:
  # - name: eth0
  - path: '/etc/sysconfig/network-scripts/ifcfg-eth0'
    regexp: '^DEFROUTE='
    line: 'DEFROUTE=no'
  # - name: eth1
  - path: '/etc/sysconfig/network-scripts/ifcfg-eth1'
    regexp: '^GATEWAY='
    line: 'GATEWAY={{ ip_gateway }}'

  - path: "/etc/sysconfig/network-scripts/route-eth1"
    line: "default via 192.168.0.1 dev eth1 table main"
    regexp: "^default via"
  # - name: eth2
  - path: "/etc/iproute2/rt_tables"
    line: "200 eth2"
    regexp: "^200"
  - path: "/etc/sysconfig/network-scripts/route-eth2"
    line: "192.168.0.32/28 dev eth2 table eth2"
    regexp: "^192.168.0.32/28"
  - path: "/etc/sysconfig/network-scripts/route-eth2"
    line: "default via 192.168.0.33 dev eth2 table eth2"
    regexp: "^default via"
  - path: "/etc/sysconfig/network-scripts/rule-eth2"
    line: "from 192.168.0.32/28 lookup eth2"
    regexp: "^default via "
  # - name: eth3
  - path: "/etc/iproute2/rt_tables"
    line: "201 eth3"
    regexp: "^201"
  - path: "/etc/sysconfig/network-scripts/route-eth3"
    line: "192.168.0.64/26 dev eth3 table eth3"
    regexp: "^192.168.0.64/26"
  - path: "/etc/sysconfig/network-scripts/route-eth3"
    line: "default via 192.168.0.65 dev eth3 table eth3"
    regexp: "^default via"
  - path: "/etc/sysconfig/network-scripts/rule-eth3"
    line: "from 192.168.0.64/26 lookup eth3"
    regexp: "^default via "
  # - name: eth4
  - path: "/etc/iproute2/rt_tables"
    line: "202 eth4"
    regexp: "^202"
  - path: "/etc/sysconfig/network-scripts/route-eth4"
    line: "192.168.0.16/28 dev eth4 table eth4"
    regexp: "^192.168.0.16/28"
  - path: "/etc/sysconfig/network-scripts/route-eth4"
    line: "default via 192.168.0.17 dev eth4 table eth4"
    regexp: "^default via"
  - path: "/etc/sysconfig/network-scripts/rule-eth4"
    line: "from 192.168.0.16/28 lookup eth4"
    regexp: "^default via "
  # - name: eth5
  - path: "/etc/iproute2/rt_tables"
    line: "203 eth5"
    regexp: "^203"
  - path: "/etc/sysconfig/network-scripts/route-eth5"
    line: "192.168.0.48/28 dev eth5 table eth5"
    regexp: "^192.168.0.48/28"
  - path: "/etc/sysconfig/network-scripts/route-eth5"
    line: "default via 192.168.0.49 dev eth5 table eth5"
    regexp: "^default via"
  - path: "/etc/sysconfig/network-scripts/rule-eth5"
    line: "from 192.168.0.48/28 lookup eth5"
    regexp: "^default via "

  # - name: eth6
  - path: "/etc/iproute2/rt_tables"
    line: "204 eth6"
    regexp: "^204"
  - path: "/etc/sysconfig/network-scripts/route-eth6"
    line: "192.168.0.128/25 dev eth6 table eth6"
    regexp: "^192.168.0.128/25"
  - path: "/etc/sysconfig/network-scripts/route-eth6"
    line: "default via 192.168.0.129 dev eth6 table eth6"
    regexp: "^default via"
  - path: "/etc/sysconfig/network-scripts/rule-eth6"
    line: "from 192.168.0.128/25 lookup eth6"
    regexp: "^default via "
  #
  # 192.168.0.48/28  newnet3
  # 192.168.0.128/25 newnet1