---
  ip_gateway: "192.168.2.1"
  
  lineinfile:
    # - name: eth0
    - path: '/etc/sysconfig/network-scripts/ifcfg-eth0'
      regexp: '^DEFROUTE='
      line: 'DEFROUTE=no'
    # - name: eth1
    - path: '/etc/sysconfig/network-scripts/ifcfg-eth1'
      regexp: '^GATEWAY='
      line: 'GATEWAY={{ ip_gateway }}'
  
    - path: "/etc/sysconfig/network-scripts/route-eth1"
      line: "default via 192.168.2.1"
      regexp: "^default via"
    # - name: eth2
    - path: "/etc/iproute2/rt_tables"
      line: "200 eth2"
      regexp: "^200"
    - path: "/etc/sysconfig/network-scripts/route-eth2"
      line: "192.168.2.64/26 dev eth2 table eth2"
      regexp: "^192.168.2.64/26"
    - path: "/etc/sysconfig/network-scripts/route-eth2"
      line: "default via 192.168.2.65 dev eth2 table eth2"
      regexp: "^default via"
    - path: "/etc/sysconfig/network-scripts/rule-eth2"
      line: "from 192.168.2.64/26 lookup eth2"
      regexp: "^from 192.168.2.64/26"
    # - name: eth3
    - path: "/etc/iproute2/rt_tables"
      line: "201 eth3"
      regexp: "^201"
    - path: "/etc/sysconfig/network-scripts/route-eth3"
      line: "192.168.2.128/26 dev eth3 table eth3"
      regexp: "^192.168.2.128/26"
    - path: "/etc/sysconfig/network-scripts/route-eth3"
      line: "default via 192.168.2.129 dev eth3 table eth3"
      regexp: "^default via"
    - path: "/etc/sysconfig/network-scripts/rule-eth3"
      line: "from 192.168.2.128/26 lookup eth3"
      regexp: "^from 192.168.2.128/26"
    # - name: eth4
    - path: "/etc/iproute2/rt_tables"
      line: "202 eth4"
      regexp: "^202"
    - path: "/etc/sysconfig/network-scripts/route-eth4"
      line: "192.168.2.192/28 dev eth4 table eth4"
      regexp: "^192.168.2.192/28"
    - path: "/etc/sysconfig/network-scripts/route-eth4"
      line: "default via 192.168.2.193 dev eth4 table eth4"
      regexp: "^default via"
    - path: "/etc/sysconfig/network-scripts/rule-eth4"
      line: "from 192.168.2.192/28 lookup eth4"
      regexp: "^from 192.168.2.192/28"

