---
  ip_gateway: "192.168.255.9"
  lineinfile:
    - path: '/etc/sysconfig/network-scripts/ifcfg-eth0'
      regexp: '^DEFROUTE='
      line: 'DEFROUTE=no'
    - path: '/etc/sysconfig/network-scripts/ifcfg-eth1'
      regexp: '^GATEWAY='
      line: 'GATEWAY={{ ip_gateway }}'