# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.synced_folder ".", "/vagrant", disabled: true
  
   config.vm.provision "ansible" do |ansible|
    #  ansible.verbose = "vvv"
     ansible.playbook = "provision.yaml"
     ansible.become = "true"
     ansible.groups = {
        "all" => ["ipaserver.test.local",
                  "ipaclient.test.local"],
        "ipaclients" => ["ipaclient.test.local"],
        "ipaserver" => ["ipaserver.test.local"]

      }
     ansible.raw_arguments = ['--diff']
   end
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  
    config.vm.define "ipaserver.test.local" do |server|
      server.vm.network "private_network", ip: "192.168.50.9"
      server.vm.hostname = "ipaserver.test.local"

    end
    config.vm.define "ipaclient.test.local" do |ipaclient|
      ipaclient.vm.network "private_network", ip: "192.168.50.20"
      ipaclient.vm.hostname = "ipaclient.test.local"
    end
  
  end