{
 "title": "Otus HM 15",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total {{instance}}" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available  {{instance}}" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used {{instance}}"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "la5 {{instance}}" },
    { "expr": "node_load1", "legendFormat": "la1 {{ instance }}" },
    { "expr": "node_load15", "legendFormat": "la15 {{ instance }}" }
   ]
  },
  {
   "title": "Disks Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes - node_filesystem_avail_bytes {fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{ device }} {{ instance }}"
    },
    {
     "expr": "node_filesystem_size_bytes {fstype=~\"ext4|xfs\"}",
     "legendFormat": " max {{ device }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=~\"eth.+\"}[5m])*8",
     "legendFormat": "{{device}}_out {{ instance }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device=~\"eth.+\"}[5m])*8",
     "legendFormat": "{{device}}_in {{ instance }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "# Otus-Linux 2020\n\n# Chudakov Aleksandr\n\n\n         "
   }
  }
 ]
}