---
firewalld_open_port:
  - port: "22"
  - port: "9100"
  - port: "9090"
  - port: "3000"
  - port: "9093"

prometheus_targets:
  node:
  - targets:
    - "nginx:9100"
    - "app1:9100"
    - "app2:9100"
    - "db1:9100"
    - "db2:9100"
    - "backup:9100"
    - "log:9100"
    - "monitoring:9100"
    labels:
      env: demo_otus

prometheus_alertmanager_config:
  - scheme: http
    # path_prefix: 
    # basic_auth:
    #   username: user
    #   password: pass
    static_configs:
      - targets: ["127.0.0.1:9093"]
    # proxy_url: "127.0.0.2"



grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://127.0.0.1:9090'
    basicAuth: false

grafana_dashboards:
  - dashboard_id: 1860
    revision_id: 21
    datasource: prometheus


alertmanager_version: latest
alertmanager_receivers:
  - name: slack
    slack_configs:
      - send_resolved: true
        channel: '#alerting'
alertmanager_route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: slack