---
prometheus_targets:
  node:
  - targets:
    - "nginx:9100"
    - "app1:9100"
    - "app2:9100"
    - "db1:9100"
    - "db2:9100"
    - "backup:9100"
    - "log:9100"
    - "monitoring:9100"
    labels:
      env: demo_otus

grafana_security:
  admin_user: otus
  admin_password: Otus2021

grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://127.0.0.1:9090'
    basicAuth: false

grafana_dashboards:
  - dashboard_id: 1860
    revision_id: 21
    datasource: prometheus