all:
  hosts:
    vagrant_1:
      ansible_host: "{{ ansible_ssh_host }}"
      ansible_ssh_host: 127.0.0.1
      ansible_ssh_port: 2222
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/nginx/virtualbox/private_key
      # ansible_python_interpreter: /usr/bin/python3

pam:
  hosts:
    vagrant_1:
  vars:
    users: 
      - name: "admin"
        pass: "{{ 'Otus2019' | password_hash('sha512') }}"
        group: ""
      - name: "user1"
        pass: "{{ 'Otus2019' | password_hash('sha512') }}"
        group: admin
      - name: "user2"
        pass: "{{ 'Otus2019' | password_hash('sha512') }}"
        group: ""
      - name: "vagrant"
        pass: "{{ 'Otus2019' | password_hash('sha512') }}"
        group: "admin"






